/* eslint-disable @next/next/no-title-in-document-head */
import LoadingPage from '@/components/shared/LoadingPage'

import { Head, Html, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang='en'>
      <Head>
        <title>Thanh Tùng</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body>
        <LoadingPage />
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
